name: Build and Upload Flutter MacOS Application

on:
  pull_request:
    branches: [main]
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build-and-upload:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'

      - name: Install dependencies
        run: flutter pub get

      - name: Build MacOS Application
        run: flutter build macos

      - name: Upload Artifact (PR and Push)
        if: github.event_name != 'release'
        uses: actions/upload-artifact@v4
        with:
          name: macos-application
          path: build/macos/Build/Products/Release/*.app

      - name: Upload Artifact to Release
        if: github.event_name == 'release'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./build/macos/Build/Products/Release/*.app
          asset_name: MacOS_Application.app
          asset_content_type: application/octet-stream
